/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import java.lang.Math;
import java.util.List;
import java.util.ListIterator;
import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static <T> List<T> zip(List<T> list_1, List<T> list_2){
        List<T> result_list = new ArrayList<T>();
        int max_ind;
        boolean list_1_is_longer = false;
        if(list_1.size() > list_2.size()){
            max_ind = list_2.size();
            list_1_is_longer = true;
        }
        else if (list_1.size() < list_2.size()){
            max_ind = list_1.size();
        }
        else  max_ind = list_1.size();


        for(int ind = 0; ind < max_ind; ind++){
            result_list.add(list_1.get(ind));
            result_list.add(list_2.get(ind));

        }

        int last_elements = Math.abs(list_1.size()-list_2.size());

        System.out.println(last_elements);

        if(last_elements==0) return result_list;

        if(list_1_is_longer){
            for(int ind = max_ind; ind < list_1.size(); ind++){
                result_list.add(list_1.get(ind));
            }
        }
        else{
            for(int ind = max_ind; ind < list_2.size(); ind++){
                result_list.add(list_2.get(ind));
            }
        }
        return result_list;
    }

    public static void main(String[] args) {
        List<Integer> nums1 = List.of(1, 3, 5, 7);
        List<Integer> nums2 = List.of(2, 4, 6, 8);
        List<Integer> mergedNumbers = zip(nums1, nums2);
        System.out.println(mergedNumbers); // [1, 2, 3, 4, 5, 6, 7, 8]

        List<String> colors1 = List.of("Red", "Green", "Blue");
        List<String> colors2 = List.of("White", "Black", "Orange", "Pink", "Fuschia");
        List<String> mergedWords = zip(colors1, colors2);
        System.out.println(mergedWords); // ["Red", "White", "Green", "Black", "Blue", "Orange", "Pink", "Fuschia"]
    }

}
